name: fusion_mobile_revamped
description: Fusion Mobile
version: 1.2.26+255
# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version numberoptional build number separated by a +.
  ## Both the version and the builder number may be overridden in flutter
  ## build by specifying --build-name and --build-number, respectively.
  ## In Android, build-name is used as versionName while build-number used as versionCode.
  ## Read more about Android versioning at https://developer.android.com/studio/publish/versioning
  ## In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
  ## Read more about iOS versioning at
## https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#version: 1.0.0 is three numbers separated by dots, like 1.2.43
# followed by an

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # flutter_apns: ^1.6.0
  encrypt: ^5.0.3
  crypto: ^3.0.2
  firebase_core: ^2.17.0
  firebase_messaging: ^14.6.9
  firebase_core_platform_interface: ^4.8.0
  flutter_dtmf: ^2.0.2
  # android_intent_plus: ^5.0.0
  # websocket_manager:
  flutter_gravatar: ^2.0.2
  ringtone_player: ^0.1.1
  awesome_notifications: ^0.7.4+1
  sip_ua:
    path: "./dart-sip-ua"
  http: ^1.1.0
  keyboard_attachable: ^2.1.0
  web_socket_channel: ^2.4.0
  flutter_local_notifications: ^16.1.0
  cupertino_icons: ^1.0.6
  url_launcher: ^6.1.11
  modal_bottom_sheet: ^2.1.2
  video_player: ^2.7.2
  sqflite: ^2.2.8+4
  path: ^1.8.2
  flutter_spinkit: ^5.2.0
  image_picker: ^1.0.4
  photo_view: ^0.14.0
  permission_handler: ^11.0.1
  mime: ^1.0.4
  just_audio: ^0.9.35
  dotted_border: ^2.1.0
  audioplayers: ^5.2.0
  cookie_jar: ^4.0.8
  shared_preferences: ^2.2.1
  all_sensors: ^0.4.2
  callkeep:
    path: "./callkeap"
  # flutter_incall_manager:
  #   path: "./flutter-incall-manager"
 #   git:
    #  url: https://github.com/davidkarn/callkeep.git
  flutter_background: ^1.2.0
  overlay_support: ^2.1.0
  path_provider: ^2.1.1
  # flutter_audio_manager:
  connectivity_plus: ^5.0.0
  internet_connection_checker: ^1.0.0+1
  flutter_exif_rotation: ^0.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/
    - assets/audio/
    - assets/crm_icons/
    - assets/icons/
    - assets/icons/hamburger.png
    - assets/icons/down_chevron.png
    - assets/icons/call_view/
    - assets/icons/call_view/toolbar/
    - assets/background.png
    - assets/icons/messages/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  #
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
